### ISSUE TITLE
Fails to build on Python 3.12 -  error: use of undeclared identifier 'PyUnicode_FromUnicode'

### ISSUE THREAD

**Issue by NyankoAndMamenoki** [ikegami-yukino/neologdn#25]
Python 3.12の環境において、インストールを行うと以下のエラーが発生します。

```
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'neologdn' extension
      creating build
      creating build/temp.macosx-11.0-arm64-cpython-312
      clang -fno-strict-overflow -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /Users/my_name/mambaforge/envs/env_py12/include -arch arm64 -fPIC -O2 -isystem /Users/my_name/mambaforge/envs/env_py12/include -arch arm64 -I/Users/my_name/mambaforge/envs/env_py12/include/python3.12 -c neologdn.cpp -o build/temp.macosx-11.0-arm64-cpython-312/neologdn.o -std=c++11 -mmacosx-version-min=10.7 -stdlib=libc++
      neologdn.cpp:6454:15: error: use of undeclared identifier 'PyUnicode_FromUnicode'
        __pyx_t_8 = __Pyx_PyUnicode_FromUnicode(__pyx_v_buf); if (unlikely(!__pyx_t_8)) __PYX_ERR(0, 192, __pyx_L1_error)
                    ^
      neologdn.cpp:1206:46: note: expanded from macro '__Pyx_PyUnicode_FromUnicode'
      #define __Pyx_PyUnicode_FromUnicode(u)       PyUnicode_FromUnicode(u, __Pyx_Py_UNICODE_strlen(u))
                                                   ^
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for neologdn
ERROR: Could not build wheels for neologdn, which is required to install pyproject.toml-based projects

failed

CondaEnvException: Pip failed
```

## 環境
- macOS Sonoma 14.2.1
- CPU = Apple M1 
- conda系のツールであるmambaを使用しています
  - pipを使って他のツールはインストールできています（japanize-matplotlib）
  - Python3.11では動作しています

**Comment by ikegami-yukino** [comment]
@NyankoAndMamenoki 
報告ありがとうございます。
さっそくこの問題はバージョン0.5.3で解消されました！
