### ISSUE TITLE
Fails to build on Python 3.11 - longintrepr.h: No such file or directory

### ISSUE THREAD

**Issue by takapy0210** [ikegami-yukino/neologdn#23]
Python 3.11の環境において、インストールを行うと以下のエラーが発生します。

```sh
Using version ^0.5.1 for neologdn

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing neologdn (0.5.1): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  running bdist_wheel
  running build
  running build_ext
  building 'neologdn' extension
  creating build
  creating build/temp.linux-aarch64-cpython-311
  gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/tmpr_sufb23/.venv/include -I/usr/local/include/python3.11 -c neologdn.cpp -o build/temp.linux-aarch64-cpython-311/neologdn.o -std=c++11
  neologdn.cpp:198:12: fatal error: longintrepr.h: No such file or directory
    198 |   #include "longintrepr.h"
        |            ^~~~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  

  at /usr/local/lib/python3.11/site-packages/poetry/installation/chef.py:147 in _prepare
      143│ 
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│ 
      146│             if error is not None:
    → 147│                 raise error from None
      148│ 
      149│             return path
      150│ 
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with neologdn (0.5.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "neologdn (==0.5.1)"'.
```

https://github.com/aio-libs/aiohttp/issues/6600 のISSUEにも記載されていますが、3.11起因で発生するエラーのようです（3.10だと発生しません）
具体的なWorkAroundに関してはまだ分かっていませんが、取り急ぎ共有までに。

**Comment by polm** [comment]
workaround として、ソースからビルドすることができます。

```
pip install cython
pip install neologdn --no-binary :all:
```

**Comment by ikegami-yukino** [comment]
@takapy0210 
最新版をPyPIにアップロードしました。
`pip install neologdn`
で試してみてください！

**Comment by takapy0210** [comment]
@ikegami-yukino 
すみません、返信を失念しておりました。
対応ありがとうございます！！！！
